image: registry.es.av.it.pt/cicd/archmaker

stages:
  - deploy release
  - deploy debug

deploy release:
  stage: deploy release
  resource_group: packaging
  script:
    - curl --fail-with-body --silent http://es-lbs.av.it.pt:3000/archlinux/x86/it2s-rsock-git
    - curl --fail-with-body --silent http://es-lbs.av.it.pt:3000/ubuntu/focal/arm64/it2s-rsock-git
    - curl --fail-with-body --silent http://es-lbs.av.it.pt:3000/ubuntu/jammy/amd64/it2s-rsock-git
    - curl --fail-with-body --silent http://es-lbs.av.it.pt:3000/ubuntu/noble/arm64/it2s-rsock-git

deploy debug:
  stage: deploy debug
  resource_group: packaging
  script:
    - curl --fail-with-body --silent http://es-lbs.av.it.pt:3000/archlinux/x86/it2s-rsock-debug-git
    - curl --fail-with-body --silent http://es-lbs.av.it.pt:3000/ubuntu/focal/arm64/it2s-rsock-debug-git
    - curl --fail-with-body --silent http://es-lbs.av.it.pt:3000/ubuntu/jammy/amd64/it2s-rsock-debug-git
    - curl --fail-with-body --silent http://es-lbs.av.it.pt:3000/ubuntu/noble/arm64/it2s-rsock-debug-git
