apiVersion: v1
kind: ConfigMap
metadata:
  name: http-sink-conf
  namespace: default
data:
  default.conf: |
    server {
      listen 8080;
      location / {
        return 200 'ok';
        add_header Content-Type text/plain;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-sink
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-sink
  template:
    metadata:
      labels:
        app: http-sink
    spec:
      nodeSelector:
        rsu-id: "rsu-b"
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: conf
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: conf
          configMap:
            name: http-sink-conf
---
apiVersion: v1
kind: Service
metadata:
  name: http-sink
  namespace: default
spec:
  selector:
    app: http-sink
  ports:
    - port: 80
      targetPort: 8080
