# File: mec-trafficrules.yaml
apiVersion: mec.etsi.org/v1alpha1
kind: TrafficRule
metadata:
  name: live-capture-cam-traffic
  namespace: default
spec:
  trafficRuleId: "live-capture-cam-traffic"
  filterType: "FLOW"
  priority: 200
  trafficFilter:
    - srcAddress: []
      dstAddress: []
      srcPort: []
      dstPort: []
      protocol:
        - "UDP"
      dscp: []
  action: "DUPLICATE_DECAPSULATED"
  # DUPLICATE_* actions require two destination interfaces (ETSI: client side and core side)
  dstInterface:
    - interfaceType: "MAC"
    - interfaceType: "MAC"
  applicationRef:
    name: "live-capture"
    namespace: "default"
