apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: live-capture
  labels:
    app: live-capture
spec:
  selector:
    matchLabels:
      app: live-capture
  template:
    metadata:
      labels:
        app: live-capture
    spec:
      # See all node interfaces and get node network namespace
      hostNetwork: true
      dnsPolicy: None
      dnsConfig:
        nameservers: ["10.42.0.2"] 
        searches:
          - knative-eventing.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      securityContext:
        runAsUser: 0
      containers:
        - name: user-container
          image: ghcr.io/pmacoutinho/its-live-capture:latest
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: IFACE
              value: "any"  # capture from all host interfaces
            - name: BPF
              value: ""
            - name: DISPLAY_FILTER
              value: ""
            - name: LOG_EVERY
              value: "10"
            - name: CE_TYPE
              value: "its.cam"
            - name: STDOUT_NDJSON
              value: "0"
            - name: PROMISCUOUS
              value: "1"
            - name: CAPTURE_80211
              value: "1"
            - name: MONITOR
              value: "0"
            # Optional: include full frame hex in NDJSON (can be large)
            #- name: INCLUDE_RAW_HEX
            #  value: "1"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
              add: ["NET_RAW", "NET_ADMIN"]  # needed for AF_PACKET capture
          volumeMounts:
            - name: varlog
              mountPath: /var/log
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: varlog
          emptyDir: {}
