apiVersion: v1
kind: Pod
metadata:
  name: pcap-replayer
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
    - name: replayer
      image: ubuntu:22.04
      command: ["sleep","infinity"]
