apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: cam-to-logger
  namespace: default
spec:
  broker: default
  filter:
    attributes:
      type: its.cam
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: cam-logger
