apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: live-capture
  labels:
    app: live-capture
spec:
  selector:
    matchLabels:
      app: live-capture
  template:
    metadata:
      labels:
        app: live-capture
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        runAsUser: 0
      containers:
        - name: sniffer
          image: ghcr.io/pmacoutinho/live-capture-rsock:latest
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

            # capture interface
            - name: IFACE
              value: "cw-mon-rxa"
            - name: BPF
              value: ""
            - name: LOG_EVERY
              value: "10"
            - name: CE_TYPE
              value: "its.cam"
            - name: STDOUT_NDJSON
              value: "0"
            - name: PROMISCUOUS
              value: "1"
            - name: SEND_QUEUE_MAX
              value: "1000"
            # Optional: include raw frame hex in output/event data (big!)
            - name: CE_INCLUDE_RAW_HEX
              value: "1"

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
              add:
                - NET_RAW
                - NET_ADMIN   # helps for promiscuous mode; safe to keep
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
