apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: live-capture
  labels:
    app: live-capture
spec:
  selector:
    matchLabels:
      app: live-capture
  template:
    metadata:
      labels:
        app: live-capture
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        runAsUser: 0
      containers:
        - name: user-container
          image: ghcr.io/pmacoutinho/its-live-capture-rs:latest
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: IFACE
              value: "eth0"
            - name: BPF
              value: ""
            - name: DISPLAY_FILTER
              value: ""
            - name: LOG_EVERY
              value: "10"
            - name: CE_TYPE
              value: "its.cam"
            - name: STDOUT_NDJSON
              value: "1"
            - name: PROMISCUOUS
              value: "1"
            - name: RUST_LOG 
              value: "info"
            # Optional:
            # - name: INCLUDE_RAW_HEX
            #   value: "1"
            # - name: SEND_QUEUE_MAX
            #   value: "1000"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
              add: ["NET_RAW", "NET_ADMIN"]
          volumeMounts:
            - name: varlog
              mountPath: /var/log
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
      volumes:
        - name: varlog
          emptyDir: {}
