# File: mec-mobileedgeapplications.yaml
apiVersion: mec.atnog.org/v1alpha1
kind: EdgeApplication
metadata:
  name: cam-logger-operator
  namespace: default
spec:
  # --- ETSI bits ---
  dId: "cam-logger-operator-appd-v1"
  name: "cam-logger-operator"
  provider: "example.mec"
  softVersion: "1.0.0"
  dVersion: "1.0.0"
  infoName: "CAM Event Logger"
  description: "Receives CAM CloudEvents and logs them."
  # --- Vendor-specific block ---
  service:
    container:
      image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
      env:
        - name: LOG_FORMAT
          value: "pretty"
    triggerFilters:
      - type: its.cam
      - type: its.denm
  autoReplicas:
    - matchNodes:
        rsu-a: "true"
