apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: edge-app-sink
  namespace: default
spec:
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
      namespace: default
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    selector:
      matchExpressions:
        - key: mec.atnog.org/app
          operator: Exists
