apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cam-logger
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
        # containerPort is optional; Knative sets $PORT for the image.
        ports:
        - containerPort: 8080
