apiVersion: mec.atnog.org/v1alpha1
kind: EdgeApplication
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: edgeapplication-sample
spec:
  # TODO(user): Add fields here
