apiVersion: mec.atnog.org/v1alpha1
kind: EdgeApplicationHandoff
metadata:
  name: cam-logger-operator-to-rsu-a
  namespace: default
spec:
  edgeApplicationName: cam-logger-operator
  targetReplicaName: rsu-a
